"""добавление каскадного удаления для моделей Cat и Breed

Revision ID: 8f18f4a9a267
Revises: 2d1180f6a722
Create Date: 2024-10-03 16:21:45.385089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f18f4a9a267'
down_revision: Union[str, None] = '2d1180f6a722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cat_breed_id_fkey', 'cat', type_='foreignkey')
    op.create_foreign_key(None, 'cat', 'breed', ['breed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.create_foreign_key('cat_breed_id_fkey', 'cat', 'breed', ['breed_id'], ['id'])
    # ### end Alembic commands ###
